# Licensed under the Apache-2.0 license

[manifest_config]
version = 1
flags = 0
security_version = 0
prj_name = "ast2755-default"
padding_align_size = 256
padding_out_folder = "out/padding_output"

[vendor_fw_key_config]
ecc_pub_key = "vnd-fw-ecc-pub-key-1.pem"
ecc_priv_key = "vnd-fw-ecc-priv-key-1.pem"
lms_pub_key = "vnd-fw-lms-pub-key-0.pem"
lms_priv_key = "vnd-fw-lms-priv-key-0.pem"
mldsa_pub_key = "vnd-fw-mldsa-pub-key-0.bin"
mldsa_priv_key = "vnd-fw-mldsa-priv-key-0.bin"

[vendor_man_key_config]
ecc_pub_key = "vnd-man-ecc-pub-key.pem"
ecc_priv_key = "vnd-man-ecc-priv-key.pem"
lms_pub_key = "vnd-man-lms-pub-key.pem"
lms_priv_key = "vnd-man-lms-priv-key.pem"
mldsa_pub_key = "vnd-man-mldsa-pub-key.bin"
mldsa_priv_key = "vnd-man-mldsa-priv-key.bin"

[owner_fw_key_config]
ecc_pub_key = "own-fw-ecc-pub-key.pem"
ecc_priv_key = "own-fw-ecc-priv-key.pem"
lms_pub_key = "own-fw-lms-pub-key.pem"
lms_priv_key = "own-fw-lms-priv-key.pem"
mldsa_pub_key = "own-fw-mldsa-pub-key.bin"
mldsa_priv_key = "own-fw-mldsa-priv-key.bin"

[owner_man_key_config]
ecc_pub_key = "own-man-ecc-pub-key.pem"
ecc_priv_key = "own-man-ecc-priv-key.pem"
lms_pub_key = "own-man-lms-pub-key.pem"
lms_priv_key = "own-man-lms-priv-key.pem"
mldsa_pub_key = "own-man-mldsa-pub-key.bin"
mldsa_priv_key = "own-man-mldsa-priv-key.bin"

[image_runtime_list]
caliptra_file = "caliptra-fw.bin"
mcu_file = "ssmcu-runtime-ast2755.bin"

[[image_metadata_list]]
file = "ssmcu-runtime-ast2755.bin"
source = 1
fw_id = 0x0002
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_0000_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "ddr4_pmu_train_imem.bin"
source = 1
fw_id = 0x1000
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "ddr4_pmu_train_dmem.bin"
source = 1
fw_id = 0x1001
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "ddr4_2d_pmu_train_imem.bin"
source = 1
fw_id = 0x1002
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "ddr4_2d_pmu_train_dmem.bin"
source = 1
fw_id = 0x1003
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "ddr5_pmu_train_imem.bin"
source = 1
fw_id = 0x1004
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "ddr5_pmu_train_dmem.bin"
source = 1
fw_id = 0x1005
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "dp_fw.bin"
source = 1
fw_id = 0x1006
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "uefi_ast2700.bin"
source = 1
fw_id = 0x1007
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_34BA_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "trusted-firmware-a/bl31.bin"
source = 1
fw_id = 0x1008
ignore_auth_check = false
load_stage = 1
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_f000_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "optee/tee-raw.bin"
source = 1
fw_id = 0x1009
ignore_auth_check = false
load_stage = 1
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_f008_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "u-boot.bin"
source = 1
fw_id = 0x100a
ignore_auth_check = false
load_stage = 1
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_c000_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "zephyr-aspeed-ssp.bin"
source = 1
fw_id = 0x100b
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_0000_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0

[[image_metadata_list]]
file = "zephyr-aspeed-tsp.bin"
source = 1
fw_id = 0x100c
ignore_auth_check = false
load_stage = 0
exec_bit = 0
component_id = 0
image_load_address = 0x0000_0000_0000_0000
image_staging_address = 0x0000_0000_0000_0000
classification = 0
